version: 5.1.0
variant: default
logo:
  text: ao's blog
head:
  favicon: /img/favicon.ico
navbar:
  # 导航栏菜单项
  menu:
    Home: /
    Archives: /archives
    Categories: /categories
    Tags: /tags
    Works: /works
    About: /about
article:
  highlight:
    # 代码高亮主题
    # https://github.com/highlightjs/highlight.js/tree/master/src/styles
    theme: atom-one-light
    # 显示复制代码按钮
    clipboard: true
    # 代码块的默认折叠状态。可以是"", "folded", "unfolded"
    fold: unfolded
  readtime: true
  # 文章许可协议
  licenses:
    Creative Commons:
      icon: fab fa-creative-commons
      url: "https://creativecommons.org/"
    "CC BY-NC-SA 4.0": "https://creativecommons.org/licenses/by-nc-sa/4.0/"
sidebar:
  left:
    sticky: true
  right:
    sticky: true
widgets:
  - type: profile
    position: left
    # Author name
    author: ao
    # Title of the author
    author_title: front-end engineer
    # Author location/organization
    location: China
    # URL of the avatar/profile picture
    avatar: /img/avatar.png
    # Whether to show a round clip of the avatar
    avatar_rounded: false
    # The email address of the Gravatar service(if the `avatar` is not set)
    gravatar:
    # The follow link URL
    follow_link: "https://github.com/aoGmg"
    # Social media link URLs
  - type: recent_posts
    position: right
  - type: tags
    position: left
  - type: categories
    position: left
comment:
  type: gitalk
  client_id: a86575089310f19071f7
  client_secret: d30735ef42dea52f1c93ff6d75bc346281350024
  repo: hexo-comment
  owner: aoGmg
  admin:
    - aoGmg
  per_page: 20 # 可选填
  distraction_free_mode: false # 可选填
  pager_direction: last # 可选填
  create_issue_manually: false # 可选填
  proxy: # 可选填
  flip_move_options: # 可选填
  enable_hotkey: true # 可选填
  language: en # 可选填
  # language: zh-CN # 可选填
