inject:
  head:
    - <link rel="preconnect" href="https://fonts.googleapis.com">
    - <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    - <link href="https://fonts.googleapis.com/css2?family=Ubuntu+Mono:ital,wght@0,400;0,700;1,400;1,700&display=swap" rel="stylesheet">
    # - <link href="https://cdn.jsdelivr.net/npm/@callmebill/lxgw-wenkai-web@latest/lxgwwenkai-regular/result.css" rel="stylesheet">
    - <link href="https://fonts.cdnfonts.com/css/opposans" rel="stylesheet">

style:
  font-size:
    root: 16px
    body: .9375rem # 15px
    code: 85% # 14px
    codeblock: 0.8125rem # 13px
  font-family:
    logo: '"Ubuntu Mono", monospace'
    # body: 'OPPOSans, "LXGW WenKai", "Ubuntu Mono", monospace'
    body: 'OPPOSans, "Ubuntu Mono", monospace'
    code: '"Ubuntu Mono", monospace'
    codeblock: '"Ubuntu Mono", monospace'

search:
  service: local_search
  local_search:
    field: all
    path: /search.json
    content: true
    codeblock: true

lazyload:
  enable: true
  js: https://gcore.jsdelivr.net/npm/vanilla-lazyload@17.3.1/dist/lazyload.min.js
  transition: fade
