version: 5.1.0
variant: default
logo:
  text: ao's blog
head:
  favicon: /img/favicon.ico
navbar:
  # 导航栏菜单项
  menu:
    Home: /
    Archives: /archives
    Categories: /categories
    Tags: /tags
    Works: /works
    About: /about
article:
  highlight:
    # 代码高亮主题
    # https://github.com/highlightjs/highlight.js/tree/master/src/styles
    theme: atom-one-light
    # 显示复制代码按钮
    clipboard: true
    # 代码块的默认折叠状态。可以是"", "folded", "unfolded"
    fold: folded
  readtime: true
  # 文章许可协议
  licenses:
    Creative Commons:
      icon: fab fa-creative-commons
      url: "https://creativecommons.org/"
    "CC BY-NC-SA 4.0": "https://creativecommons.org/licenses/by-nc-sa/4.0/"
sidebar:
  left:
    sticky: false
  right:
    sticky: false
widgets:
  - type: profile
    position: left
    # Author name
    author: ao
    # Title of the author
    author_title: front-end engineer
    # Author location/organization
    location: China
    # URL of the avatar/profile picture
    avatar: /img/avatar-ts.png
    # Whether to show a round clip of the avatar
    avatar_rounded: false
    # The email address of the Gravatar service(if the `avatar` is not set)
    gravatar:
    # The follow link URL
    follow_link: "https://github.com/aoGmg"
    # Social media link URLs
  - type: recent_posts
    position: right
  - type: tags
    position: left
  - type: categories
    position: left
comment:
  type: gitalk
  client_id: a86575089310f19071f7
  client_secret: d30735ef42dea52f1c93ff6d75bc346281350024
  repo: hexo-comment
  owner: aoGmg
  admin:
    - aoGmg
  per_page: 20 # 可选填
  distraction_free_mode: false # 可选填
  pager_direction: last # 可选填
  create_issue_manually: false # 可选填
  proxy: # 可选填
  flip_move_options: # 可选填
  enable_hotkey: true # 可选填
  language: en # 可选填
  # language: zh-CN # 可选填
plugins:
  bing_webmaster:
    tracking_id: FA0DD8FC4D76C8D0698C0DC0A2E39C26
  gallery: true
  cookie_consent:
    # 同意对话框类型。可以为"info"，"opt-in"，或"opt-out"
    type: info
    # 弹出框主题。可以为"block"，"edgeless"，或"classic"
    theme: edgeless
    # 是否使弹出框固定，不随页面滚动而滚动
    static: false
    # 弹出框在屏幕上的位置
    position: bottom-right
    # 你网站的Cookie协议的URL
    policyLink: "https://www.cookiesandyou.com/"
  outdated_browser: true
  animejs: true
  progressbar: true
donates:
  - type: alipay
    # 个人赞助页面的地址
    qrcode: /img/alipay-receive.jpg
  - type: wechat
    qrcode: /img/wechat-receive.jpg
search:
  type: insight
  include_pages: true # 可选项。设置为false时从搜索结果中排除所有page
share:
  type: addtoany
